# Generated by Django 3.2 on 2021-06-11 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_Bundle', models.CharField(max_length=255, unique=True)),
                ('Count_channels', models.IntegerField(default=None, null=True)),
                ('Count_films', models.IntegerField(default=None, null=True)),
                ('Price', models.IntegerField()),
                ('Date_begin', models.DateField(null=True)),
                ('Date_end', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_Operator', models.CharField(max_length=255)),
                ('Login', models.CharField(max_length=30, unique=True)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_Town', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_Street', models.CharField(max_length=255)),
                ('Town', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SCourse.town')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_Client', models.CharField(max_length=255)),
                ('Phone_Number', models.IntegerField()),
                ('House', models.CharField(max_length=5)),
                ('Entrance', models.IntegerField()),
                ('Floor', models.IntegerField()),
                ('Flat', models.IntegerField()),
                ('Status', models.BooleanField(default=False, null=True)),
                ('Bundle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SCourse.bundle')),
                ('Operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SCourse.operator')),
                ('Street', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SCourse.street')),
                ('Town', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SCourse.town')),
            ],
        ),
    ]
