# Generated by Django 3.2 on 2021-06-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCourse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='Date_application',
            field=models.DateField(null=True),
        ),
    ]
