# Generated by Django 3.2 on 2021-06-13 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCourse', '0002_application_date_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Date_application',
            field=models.DateField(default=datetime.date(2021, 6, 13), null=True),
        ),
    ]
